# Generated by Django 5.0.3 on 2024-07-29 22:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0005_alter_walletaddress_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Telegram',
            new_name='AdminTelegram',
        ),
    ]
