# Generated by Django 5.0.3 on 2024-07-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0007_simpleorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='simple_orders/'),
        ),
    ]
