# Generated by Django 5.0.3 on 2024-08-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0010_alter_submission_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_submission', to='adminControl.simpleorder'),
        ),
    ]
