# Generated by Django 5.0.3 on 2024-08-01 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0013_alter_simpleorder_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleorder',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='simpleorder',
            name='customer',
        ),
        migrations.CreateModel(
            name='SubmittedOrder',
            fields=[
                ('simpleorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminControl.simpleorder')),
                ('is_submitted', models.BooleanField(default=False)),
                ('check_box', models.BooleanField(default=False)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_orders', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('adminControl.simpleorder',),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
