# Generated by Django 5.0.3 on 2024-08-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0014_remove_simpleorder_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
