# Generated by Django 5.0.3 on 2024-08-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0016_alter_simpleorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedorder',
            name='index',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
