# Generated by Django 5.0.3 on 2024-08-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0017_submittedorder_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedorder',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
