# Generated by Django 5.0.3 on 2024-08-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0021_remove_simpleorder_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='label',
            field=models.CharField(default='simple', max_length=10),
        ),
    ]
