# Generated by Django 5.0.3 on 2024-08-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0022_simpleorder_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleorder',
            name='label',
            field=models.CharField(max_length=10),
        ),
    ]
