# Generated by Django 5.0.3 on 2024-08-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0024_batch_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='lucky_orders', to='adminControl.product'),
        ),
    ]
