# Generated by Django 5.0.3 on 2024-08-13 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0026_order_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_batch_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_copies', to='adminControl.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_lucky_order_position', models.IntegerField(blank=True, null=True)),
                ('custom_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to='adminControl.product')),
                ('custom_products', models.ManyToManyField(blank=True, related_name='custom_lucky_orders', to='adminControl.product')),
                ('customer_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='adminControl.customerbatch')),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_copies', to='adminControl.order')),
            ],
        ),
    ]
