# Generated by Django 5.0.3 on 2024-08-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0027_customerbatch_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
