# Generated by Django 5.0.3 on 2024-08-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0028_customerorder_is_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedorder',
            name='simpleorder_ptr',
        ),
        migrations.RemoveField(
            model_name='submittedorder',
            name='submitted_by',
        ),
        migrations.DeleteModel(
            name='SimpleOrder',
        ),
        migrations.DeleteModel(
            name='SubmittedOrder',
        ),
    ]
