# Generated by Django 5.0.3 on 2024-08-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0029_remove_submittedorder_simpleorder_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ali_baba_logo', models.ImageField(upload_to='Logo')),
                ('about_ist', models.ImageField(upload_to='about_pics')),
                ('about_2nd', models.ImageField(upload_to='about_pics')),
                ('about_3rd', models.ImageField(upload_to='about_pics')),
                ('about_4th', models.ImageField(upload_to='about_pics')),
                ('about_5th', models.ImageField(upload_to='about_pics')),
            ],
        ),
    ]
