# Generated by Django 5.0.3 on 2024-08-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0030_extrapictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
