# Generated by Django 5.0.3 on 2024-07-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedeposit',
            name='total_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
