# Generated by Django 5.0.3 on 2024-07-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
    ]
