# Generated by Django 5.0.3 on 2024-07-28 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customer_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpassword',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_password', to=settings.AUTH_USER_MODEL),
        ),
    ]
