# Generated by Django 5.0.3 on 2024-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wallet_address',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
