# Generated by Django 5.0.3 on 2024-07-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_wallet_address_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_wallet_address',
            old_name='user_wallet_address',
            new_name='user',
        ),
    ]
