# Generated by Django 5.0.7 on 2024-08-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_user_wallet_address_user_wallet_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wallet_address',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
