# Generated by Django 5.0.3 on 2024-08-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_wallet_address_address'),
        ('adminControl', '0026_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='users', to='adminControl.batch'),
        ),
    ]
