# Generated by Django 5.0.3 on 2024-08-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='login_ip',
            field=models.CharField(default='..', max_length=100),
            preserve_default=False,
        ),
    ]
