# Generated by Django 5.0.3 on 2024-08-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userip_login_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='login_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
