# Generated by Django 5.0.3 on 2024-07-28 07:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('today_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deposited_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deposited Amount')),
                ('deposit_method', models.CharField(max_length=70, verbose_name='Deposit Method')),
                ('wallet_address', models.CharField(max_length=100, verbose_name='Wallet Address')),
                ('is_amount_received', models.BooleanField(default=False, verbose_name='Is Amount Received')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id_card_front', models.FileField(upload_to='kyc_documents/')),
                ('id_card_back', models.FileField(upload_to='kyc_documents/')),
                ('face_video', models.FileField(upload_to='kyc_videos/')),
                ('wallet_type', models.CharField(max_length=100)),
                ('wallet_address', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Withdrawal Amount')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed (Verification)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
